api_platform:
    show_webby: false
    title: 'EasyCoach Api Rest '   
    description: 'A Symfony API to manage Easy Coach app.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
doctrine:
    orm:
        filters:
            user_filter:
                class: App\Filter\UserFilter
            marque_filter:
                class: App\Filter\MarqueFilter

